services:
  web:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    
  api: 
    container_name: backend
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/school
    volumes:
      - ./backend:/app

  db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - school:/data/db

volumes:
  school:
